language: php

git:
  depth: 1

php:
  - '7.4.1'

# todo disable it after GraphQL bundle config fix
# see \Overblog\GraphQLBundle\DependencyInjection\Configuration::definitionsSchemaSection() call: ->setDeprecated()
env:
  global:
    - SYMFONY_DEPRECATIONS_HELPER=disabled

sudo: false

before_install:
  - if [[ $COVERAGE != true ]]; then phpenv config-rm xdebug.ini || true; fi

install:
  - composer install
  - ./vendor/bin/simple-phpunit install

script:
  - ./vendor/bin/simple-phpunit -c ./phpunit.xml.dist
