Mutation:
  type: object
  config:
    fields:
      createTask:
        type: ID!
        resolve: "@=mutation('create_task', arguments({input: 'CreateTaskInput'}, args))"
        args:
          input:
            type: CreateTaskInput!
            validation: cascade
      updateTask:
        type: ID!
        resolve: "@=mutation('update_task', arguments({input: 'UpdateTaskInput'}, args))"
        args:
          input:
            type: UpdateTaskInput!
            validation: cascade
      deleteTask:
        type: Boolean!
        resolve: "@=mutation('delete_task', arguments({input: 'ID!'}, args))"
        args:
          input:
            type: ID!
      createTaskProperty:
        type: ID!
        resolve: "@=mutation('create_task_property', arguments({input: 'CreateTaskPropertyInput'}, args))"
        args:
          input:
            type: CreateTaskPropertyInput!
            validation: cascade
      updateTaskProperty:
        type: Boolean!
        resolve: "@=mutation('update_task_property', arguments({input: 'UpdateTaskPropertyInput'}, args))"
        args:
          input:
            type: UpdateTaskPropertyInput!
            validation: cascade
      deleteTaskProperty:
        type: Boolean!
        resolve: "@=mutation('delete_task_property', arguments({input: 'ID!'}, args))"
        args:
          input:
            type: ID!
      createTaskStatus:
        type: ID!
        resolve: "@=mutation('create_task_status', arguments({input: 'CreateTaskStatusInput'}, args))"
        args:
          input:
            type: CreateTaskStatusInput!
            validation: cascade
      updateTaskStatus:
        type: Boolean!
        resolve: "@=mutation('update_task_status', arguments({input: 'UpdateTaskStatusInput'}, args))"
        args:
          input:
            type: UpdateTaskStatusInput!
            validation: cascade
      deleteTaskStatus:
        type: Boolean!
        resolve: "@=mutation('delete_task_status', arguments({input: 'ID!'}, args))"
        args:
          input:
            type: ID!
