services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  Planner\TaskCoreBundle\GraphQL\Type\DateTimeType:
    tags:
      - { name: overblog_graphql.type, alias: DateTime }

  Planner\TaskCoreBundle\GraphQL\Type\TaskPriorityType:
    tags:
      - { name: overblog_graphql.type, alias: TaskPriority }

  Planner\TaskCoreBundle\GraphQL\Type\TaskStatusType:
    tags:
      - { name: overblog_graphql.type, alias: TaskStatus }

  Planner\TaskCoreBundle\GraphQL\Resolver\TaskPriorityResolver: ~
  Planner\TaskCoreBundle\GraphQL\Resolver\TaskPropertyResolver: ~
  Planner\TaskCoreBundle\GraphQL\Resolver\TaskResolver: ~
  Planner\TaskCoreBundle\GraphQL\Resolver\TaskStatusResolver: ~

  Planner\TaskCoreBundle\GraphQL\Mutation\TaskMutation: ~
